### ISSUE TITLE
Lack of Mobile Responsiveness

### ISSUE THREAD

**Issue by AmoahDevLabs** [fajar7xx/ecommerce-template-tailwind-1#1]
This template is really awesome as the sea breeze of Seychelles beach. There's one great feature which is a mandatory to modern web applications, "Mobile Responsiveness" In view of that this template would be super awesome if mobile responsiveness is implemented.

**Comment by fajar7xx** [comment]
> This template is really awesome as the sea breeze of Seychelles beach. There's one great feature which is a mandatory to modern web applications, "Mobile Responsiveness" In view of that this template would be super awesome if mobile responsiveness is implemented.

thanks for your attention. 
yes you're right. this template may not responsive. but you can develop it, cause it using tailwind

**Comment by anhnhTEKY** [comment]
Now i'm trying improve this project with my django assignment XD

**Comment by Hicode-dev** [comment]
can i contribute to this?

**Comment by fajar7xx** [comment]
> can i contribute to this?

Yes , of course

**Comment by Hicode-dev** [comment]
ok you  can assign me to the responsiveness

**Comment by Hicode-dev** [comment]
i have created a PR please could you merge it

**Comment by Hicode-dev** [comment]
hi merge my pr !!!!

**Comment by fajar7xx** [comment]
> hi merge my pr !!!!

ok. wait

**Comment by Hicode-dev** [comment]
hi i already made another PR could you merge it

**Comment by fajar7xx** [comment]
> hi i already made another PR could you merge it

ok

**Comment by Hicode-dev** [comment]
you can close the issue now

**Comment by Hicode-dev** [comment]
is there any project you would love me to contribute to ?

**Comment by fajar7xx** [comment]
18e4cb99192a83c18f8b3eb940a480b18becd9b9

**Comment by Hicode-dev** [comment]
i dont understand
